nodeLinker: node-modules

plugins:
  - checksum: 63999b4f48569c4840fbd4de40cc3351eed228674d861b98d7e398d7f25009834c8a52bcb44a2dd3229dfd39d5f79f155e2fcb3a16ea8333b6e9b79628a48b61
    path: .yarn/plugins/@yarnpkg/plugin-dedupe.cjs
    spec: "https://github.com/blimmer/yarn-plugin-dedupe/releases/download/v1.0.0-alpha.2/plugin-dedupe.js"

dedupePluginMode: always
