/* eslint-disable */
//prettier-ignore
module.exports = {
name: "@yarnpkg/plugin-dedupe",
factory: function (require) {
var plugin=(()=>{var o=Object.defineProperty;var r=Object.getOwnPropertyDescriptor;var p=Object.getOwnPropertyNames;var c=Object.prototype.hasOwnProperty;var l=(e=>typeof require<"u"?require:typeof Proxy<"u"?new Proxy(e,{get:(n,d)=>(typeof require<"u"?require:n)[d]}):e)(function(e){if(typeof require<"u")return require.apply(this,arguments);throw Error('Dynamic require of "'+e+'" is not supported')});var f=(e,n)=>{for(var d in n)o(e,d,{get:n[d],enumerable:!0})},y=(e,n,d,u)=>{if(n&&typeof n=="object"||typeof n=="function")for(let a of p(n))!c.call(e,a)&&a!==d&&o(e,a,{get:()=>n[a],enumerable:!(u=r(n,a))||u.enumerable});return e};var g=e=>y(o({},"__esModule",{value:!0}),e);var P={};f(P,{default:()=>v});var t=l("@yarnpkg/shell"),i=["always","dependabot-only","never"],w={configuration:{dedupePluginMode:{type:"string",default:"always",description:"When to deduplicate packages. `always` deduplicates all packages after any install command. `dependabot-only` deduplicates only packages that are updated by Dependabot via GitHub Actions. `never` disables auto-deduplication.",choices:i}},hooks:{afterAllInstalled:async e=>{let n=e.configuration.get("dedupePluginMode");if(!M(n))throw new Error(`Invalid dedupePluginMode: ${n}. Must be one of: ${i.join(", ")}`);if(n!=="never"){if(n==="always"){await s();return}if(n==="dependabot-only"){process.env.DEPENDABOT==="true"&&await s();return}}}}};async function s(){let e="IS_YARN_PLUGIN_DEDUPE_ACTIVE";!process.env[e]&&!process.argv.includes("dedupe")&&(process.env[e]="true",await(0,t.execute)("yarn dedupe --check")&&await(0,t.execute)("yarn dedupe"))}function M(e){return typeof e=="string"&&i.includes(e)}var v=w;return g(P);})();
return plugin;
}
};
